spring.application.name=epms

spring.datasource.url=jdbc:postgresql://localhost:5432/epms
spring.datasource.username=${EPMS_DB_USERNAME}
spring.datasource.password=${EPMS_DB_PASSWORD}

spring.jpa.open-in-view=false
